const test=require('node:test');const assert=require('node:assert/strict');const {Score,PROFILES,DEFAULT_NODES}=require('../score.js');
function session(id,interact){const s=new Score(id,{seed:927});const notes=[],chords=[];for(let i=0;i<768;i++){if(interact&&i%37===0){s.focus(DEFAULT_NODES[(i/37|0)%12]);s.motion(.7,.3);if(i%74===0)s.open(DEFAULT_NODES[(i/37|0)%12]);}notes.push(...s.next());if(i%16===0)chords.push(s.chord);}return {s,notes,chords};}
for(const id of Object.keys(PROFILES)){
  test(`${id}: visitor history changes the future arrangement, beyond direct cues`,()=>{const a=session(id,false),b=session(id,true);assert.notDeepEqual(a.notes.filter(n=>n.role==='memory'),b.notes.filter(n=>n.role==='memory'));assert.notDeepEqual(a.chords,b.chords);assert.deepEqual(session(id,true).notes,b.notes,'same input and seed reproduce the score');});
  test(`${id}: valid, bounded notes under rapid input; unknown projects ignored`,()=>{const s=new Score(id);assert.equal(s.focus('0x0B'),false);for(let i=0;i<1500;i++){s.focus(DEFAULT_NODES[i%12]);s.open(DEFAULT_NODES[i%12]);s.motion(1,100);if(i%31===0)s.gather();for(const n of s.next()){assert.ok(n.kind==='wood' ? n.note>=1&&n.note<=3 : n.note>=24&&n.note<=90);assert.ok(n.gain<=.42);assert.ok(Math.abs(n.pan)<=.8);assert.ok(Number.isFinite(n.duration)&&n.duration>0);assert.ok(n.delay>=0);}assert.ok(s.memory.length<=4);assert.ok(s.energy<=1);}assert.ok(s.emitted<18000);});
  test(`${id}: silence in interaction keeps a continuous musical foundation`,()=>{const {notes}=session(id,false);const secondsPerStep=60/PROFILES[id].bpm/4;for(let bar=0;bar<48;bar++){const at=bar*16*secondsPerStep;assert.ok(notes.some(n=>n.role==='atmosphere'&&n.step*secondsPerStep<=at+.05&&n.step*secondsPerStep+n.duration>at),'the foundation is sounding across each bar boundary');}});
}
test('assembly is one phrase until released, with no threshold chatter',()=>{const s=new Score('universe');let starts=0;for(let i=0;i<400;i++){s.setAssembly(i%2?.79:.83);const e=s.next();if(e.some(n=>n.role==='origin')&&s.step-s.originAt===1)starts++;}assert.equal(starts,1);s.setAssembly(0);s.setAssembly(1);for(let i=0;i<5;i++)s.next();assert.ok(s.step-s.originAt<8);});
test('reading removes ornament and rhythmic demand while keeping harmony',()=>{for(const id of Object.keys(PROFILES)){const a=new Score(id),b=new Score(id);b.setSection('reading');let regular=0,reading=0;for(let i=0;i<256;i++){a.motion(.5);b.motion(.5);regular+=a.next().length;reading+=b.next().length;}assert.ok(reading<regular,`${id}: ${reading} vs ${regular}`);assert.ok(reading>20);}});
